//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ebook_website.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class Categorie
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Categorie()
        {
            this.Livre = new HashSet<Livre>();
        }

        [Required(ErrorMessage = "Id catégorie est obligatoir")]
        [DisplayName("Id catégorie")]
        public int ID_Categorie { get; set; }


        [Required(ErrorMessage = "Nom de catégorie est obligatoir")]
        [DisplayName("Nom de catégorie")]
        [DataType(DataType.Text)]
        public string Nom_Categorie { get; set; }


        [Required(ErrorMessage = "Fiche catégorie est obligatoir")]
        [DisplayName("Fiche catégorie")]
        public string Id_Image { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Livre> Livre { get; set; }
    }
}
