//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ebook_website.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Livre
    {
        [Required(ErrorMessage = "Id livre est obligatoir")]
        public int ID_Livre { get; set; }

        [DataType(DataType.Text)]
        [Required(ErrorMessage = "Titre est obligatoir")]
        public string Titre { get; set; }

        [DataType(DataType.Text)]
        [Required(ErrorMessage = "Auteur est obligatoir")]
        public string Auteur { get; set; }

        [DataType(DataType.Text)]
        [Required(ErrorMessage = "Description est obligatoir")]
        public string Description { get; set; }

        [DataType(DataType.DateTime)]
        [Required(ErrorMessage = "Date de publication est obligatoire")]
        public Nullable<System.DateTime> Date_Publication { get; set; }

        [DataType(DataType.DateTime)]

        [Required(ErrorMessage = "Date d'édition est obligatoire")]
        public Nullable<System.DateTime> Date_Edition { get; set; }

        [Required(ErrorMessage = "Categorie est obligatoir")]
        public Nullable<int> ID_Categorie { get; set; }

        [Required(ErrorMessage = "Fiche image est obligatoire")]
        public string Image { get; set; }


        [Required(ErrorMessage = "Pdf est obligatoir")]
        public string PDF { get; set; }

        public virtual Categorie Categorie { get; set; }
    }
}
