//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ebook_website.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class Utilisateur
    {
        [DataType(DataType.Text)]
        public string Nom { get; set; }


        [DisplayName("Prénom")]
        [DataType(DataType.Text)]
        public string Prenom { get; set; }



        [DisplayName("Adresse mail ")]
        [DataType(DataType.EmailAddress)]
        public string Email { get; set; }


        [DisplayName("Mot de passe ")]
        [DataType(DataType.Password)]
        public string Password { get; set; }



        [DisplayName("Confirmer votre mot de passe ")]
        [DataType(DataType.Password)]
        [Compare("Password", ErrorMessage = "Mots de passe ne sont pas identiques !")]
        public string confirmePass { get; set; }
    }
}
